# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1476, 873)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(130,187,62);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(3, 0, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: rgb(130,187,62);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:18px;\n"
"background-color: rgb(130,187,62);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(78,118,34);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_menu = QtWidgets.QPushButton(self.frame_superior)
        self.btn_menu.setMinimumSize(QtCore.QSize(50, 36))
        self.btn_menu.setMaximumSize(QtCore.QSize(50, 36))
        self.btn_menu.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(78,118,34);\n"
"border-radius: 5px\n"
"}")
        self.btn_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons2/menu (2).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(36, 36))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_2.addWidget(self.btn_menu)
        self.label_2 = QtWidgets.QLabel(self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(195, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(844, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_min = QtWidgets.QPushButton(self.frame_superior)
        self.btn_min.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_min.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons2/minus (4).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_min.setIcon(icon1)
        self.btn_min.setIconSize(QtCore.QSize(36, 36))
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_2.addWidget(self.btn_min)
        self.btn_max = QtWidgets.QPushButton(self.frame_superior)
        self.btn_max.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_max.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_max.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons2/chevrons-up (3).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_max.setIcon(icon2)
        self.btn_max.setIconSize(QtCore.QSize(36, 36))
        self.btn_max.setObjectName("btn_max")
        self.horizontalLayout_2.addWidget(self.btn_max)
        self.btn_normal = QtWidgets.QPushButton(self.frame_superior)
        self.btn_normal.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_normal.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_normal.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons2/chevrons-down (3).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_normal.setIcon(icon3)
        self.btn_normal.setIconSize(QtCore.QSize(36, 36))
        self.btn_normal.setObjectName("btn_normal")
        self.horizontalLayout_2.addWidget(self.btn_normal)
        self.btn_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(230,0,0);\n"
"}")
        self.btn_cerrar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons2/x (4).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon4)
        self.btn_cerrar.setIconSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_2.addWidget(self.btn_cerrar)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(self.frame)
        self.frame_contenido.setStyleSheet("background-color: rgb(44,44,44);\n"
"border-radius: 10px;")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_menu = QtWidgets.QFrame(self.frame_contenido)
        self.frame_menu.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_menu.setStyleSheet("QFrame{\n"
"background-color: rgb(17,17,17);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(130,187,62);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(0,0,0);\n"
"font: 77 14pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(78,118,34);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(0,0,0);\n"
"font: 77 14pt \"Arial\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 16pt \"Arial\";\n"
"}\n"
"")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_4.setContentsMargins(-1, 16, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_inicio = QtWidgets.QPushButton(self.frame_menu)
        self.btn_inicio.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_inicio.setMaximumSize(QtCore.QSize(190, 50))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/estadisticas.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_inicio.setIcon(icon5)
        self.btn_inicio.setIconSize(QtCore.QSize(30, 30))
        self.btn_inicio.setObjectName("btn_inicio")
        self.verticalLayout_2.addWidget(self.btn_inicio)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.btn_basedatos = QtWidgets.QPushButton(self.frame_menu)
        self.btn_basedatos.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_basedatos.setMaximumSize(QtCore.QSize(190, 50))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons2/database (2).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_basedatos.setIcon(icon6)
        self.btn_basedatos.setIconSize(QtCore.QSize(30, 30))
        self.btn_basedatos.setObjectName("btn_basedatos")
        self.verticalLayout_2.addWidget(self.btn_basedatos)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.btn_ajustes = QtWidgets.QPushButton(self.frame_menu)
        self.btn_ajustes.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_ajustes.setMaximumSize(QtCore.QSize(190, 50))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons2/settings (2).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ajustes.setIcon(icon7)
        self.btn_ajustes.setIconSize(QtCore.QSize(30, 30))
        self.btn_ajustes.setObjectName("btn_ajustes")
        self.verticalLayout_2.addWidget(self.btn_ajustes)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.frame_menu)
        self.label.setMinimumSize(QtCore.QSize(150, 150))
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/kindpng_665376.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem7 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addWidget(self.frame_menu)
        self.frame_paginas = QtWidgets.QFrame(self.frame_contenido)
        self.frame_paginas.setStyleSheet("background-color: rgb(44,44,44);")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_paginas)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_deteccion = QtWidgets.QWidget()
        self.page_deteccion.setObjectName("page_deteccion")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_deteccion)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.page_deteccion)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("QLabel{\n"
"color:rgb(255,255,255);\n"
"font: 77 10pt \"Arial\";\n"
"background-color: transparent;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(40)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ind_temp = QtWidgets.QFrame(self.frame_3)
        self.ind_temp.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_temp.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_temp.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(180, 10, 10, 255), stop:1 rgba(180, 10, 10, 255));\n"
"")
        self.ind_temp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_temp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_temp.setObjectName("ind_temp")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ind_temp)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.ind_temp)
        self.label_4.setStyleSheet("background-color: transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.val_temp = QtWidgets.QLabel(self.ind_temp)
        self.val_temp.setStyleSheet("background-color: transparent;")
        self.val_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_temp.setObjectName("val_temp")
        self.horizontalLayout_9.addWidget(self.val_temp)
        self.label_6 = QtWidgets.QLabel(self.ind_temp)
        self.label_6.setStyleSheet("background-color: transparent;")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.horizontalLayout_14.addWidget(self.ind_temp)
        self.ind_humedad = QtWidgets.QFrame(self.frame_3)
        self.ind_humedad.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_humedad.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_humedad.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(0, 30, 255, 180), stop:1 rgba(0, 30, 180, 255));\n"
"")
        self.ind_humedad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_humedad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_humedad.setObjectName("ind_humedad")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.ind_humedad)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem11 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.ind_humedad)
        self.label_7.setStyleSheet("background-color: transparent;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.val_humedad = QtWidgets.QLabel(self.ind_humedad)
        self.val_humedad.setStyleSheet("background-color: transparent;")
        self.val_humedad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_humedad.setObjectName("val_humedad")
        self.horizontalLayout_10.addWidget(self.val_humedad)
        self.label_9 = QtWidgets.QLabel(self.ind_humedad)
        self.label_9.setStyleSheet("background-color: transparent;")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        spacerItem12 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        self.horizontalLayout_14.addWidget(self.ind_humedad)
        self.ind_luz = QtWidgets.QFrame(self.frame_3)
        self.ind_luz.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_luz.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_luz.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(150, 150, 0, 255), stop:1 rgba(150, 150, 0, 255));\n"
"")
        self.ind_luz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_luz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_luz.setObjectName("ind_luz")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ind_luz)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem13 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.ind_luz)
        self.label_10.setStyleSheet("background-color: transparent;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_12.addWidget(self.label_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.val_luz = QtWidgets.QLabel(self.ind_luz)
        self.val_luz.setStyleSheet("background-color: transparent;")
        self.val_luz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_luz.setObjectName("val_luz")
        self.horizontalLayout_11.addWidget(self.val_luz)
        self.label_12 = QtWidgets.QLabel(self.ind_luz)
        self.label_12.setStyleSheet("background-color: transparent;")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        spacerItem14 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem14)
        self.horizontalLayout_14.addWidget(self.ind_luz)
        self.ind_ph = QtWidgets.QFrame(self.frame_3)
        self.ind_ph.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_ph.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_ph.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(160, 0, 180, 255), stop:1 rgba(160, 0, 180, 255));\n"
"")
        self.ind_ph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_ph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_ph.setObjectName("ind_ph")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.ind_ph)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem15 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.ind_ph)
        self.label_13.setStyleSheet("background-color: transparent;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.val_ph = QtWidgets.QLabel(self.ind_ph)
        self.val_ph.setStyleSheet("background-color: transparent;")
        self.val_ph.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_ph.setObjectName("val_ph")
        self.horizontalLayout_12.addWidget(self.val_ph)
        self.label_15 = QtWidgets.QLabel(self.ind_ph)
        self.label_15.setStyleSheet("background-color: transparent;")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        spacerItem16 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem16)
        self.horizontalLayout_14.addWidget(self.ind_ph)
        self.ind_conductividad = QtWidgets.QFrame(self.frame_3)
        self.ind_conductividad.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_conductividad.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_conductividad.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(2, 180, 190, 255), stop:1 rgba(2, 180, 190, 255));\n"
"")
        self.ind_conductividad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_conductividad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_conductividad.setObjectName("ind_conductividad")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.ind_conductividad)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem17 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem17)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.ind_conductividad)
        self.label_16.setStyleSheet("background-color: transparent;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_16.addWidget(self.label_16)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.val_conductividad = QtWidgets.QLabel(self.ind_conductividad)
        self.val_conductividad.setStyleSheet("background-color: transparent;")
        self.val_conductividad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_conductividad.setObjectName("val_conductividad")
        self.horizontalLayout_13.addWidget(self.val_conductividad)
        self.label_18 = QtWidgets.QLabel(self.ind_conductividad)
        self.label_18.setStyleSheet("background-color: transparent;")
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_13)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        spacerItem18 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem18)
        self.horizontalLayout_14.addWidget(self.ind_conductividad)
        self.verticalLayout_29.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(40)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.ind_t_agua = QtWidgets.QFrame(self.frame_3)
        self.ind_t_agua.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_t_agua.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_t_agua.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(190, 0, 60, 255), stop:1 rgba(190, 0, 60, 255));\n"
"")
        self.ind_t_agua.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_t_agua.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_t_agua.setObjectName("ind_t_agua")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.ind_t_agua)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem19 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem19)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.ind_t_agua)
        self.label_19.setStyleSheet("background-color: transparent;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_18.addWidget(self.label_19)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.val_t_agua = QtWidgets.QLabel(self.ind_t_agua)
        self.val_t_agua.setStyleSheet("background-color: transparent;")
        self.val_t_agua.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_t_agua.setObjectName("val_t_agua")
        self.horizontalLayout_16.addWidget(self.val_t_agua)
        self.label_21 = QtWidgets.QLabel(self.ind_t_agua)
        self.label_21.setStyleSheet("background-color: transparent;")
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.verticalLayout_18.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        spacerItem20 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem20)
        self.horizontalLayout_15.addWidget(self.ind_t_agua)
        self.ind_lvl_agua = QtWidgets.QFrame(self.frame_3)
        self.ind_lvl_agua.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_lvl_agua.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_lvl_agua.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));\n"
"")
        self.ind_lvl_agua.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_lvl_agua.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_lvl_agua.setObjectName("ind_lvl_agua")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.ind_lvl_agua)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem21 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem21)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_22 = QtWidgets.QLabel(self.ind_lvl_agua)
        self.label_22.setStyleSheet("background-color: transparent;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_20.addWidget(self.label_22)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.val_lvl_agua = QtWidgets.QLabel(self.ind_lvl_agua)
        self.val_lvl_agua.setStyleSheet("background-color: transparent;")
        self.val_lvl_agua.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_lvl_agua.setObjectName("val_lvl_agua")
        self.horizontalLayout_17.addWidget(self.val_lvl_agua)
        self.label_24 = QtWidgets.QLabel(self.ind_lvl_agua)
        self.label_24.setStyleSheet("background-color: transparent;")
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        self.verticalLayout_20.addLayout(self.horizontalLayout_17)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        spacerItem22 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem22)
        self.horizontalLayout_15.addWidget(self.ind_lvl_agua)
        self.ind_lvl_ph_mas = QtWidgets.QFrame(self.frame_3)
        self.ind_lvl_ph_mas.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_lvl_ph_mas.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_lvl_ph_mas.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(17, 190, 0, 255), stop:1 rgba(17, 190, 0, 255));\n"
"")
        self.ind_lvl_ph_mas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_lvl_ph_mas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_lvl_ph_mas.setObjectName("ind_lvl_ph_mas")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.ind_lvl_ph_mas)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        spacerItem23 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem23)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_25 = QtWidgets.QLabel(self.ind_lvl_ph_mas)
        self.label_25.setStyleSheet("background-color: transparent;")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_22.addWidget(self.label_25)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.val_lvl_ph_mas = QtWidgets.QLabel(self.ind_lvl_ph_mas)
        self.val_lvl_ph_mas.setStyleSheet("background-color: transparent;")
        self.val_lvl_ph_mas.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_lvl_ph_mas.setObjectName("val_lvl_ph_mas")
        self.horizontalLayout_18.addWidget(self.val_lvl_ph_mas)
        self.label_27 = QtWidgets.QLabel(self.ind_lvl_ph_mas)
        self.label_27.setStyleSheet("background-color: transparent;")
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_18.addWidget(self.label_27)
        self.verticalLayout_22.addLayout(self.horizontalLayout_18)
        self.verticalLayout_21.addLayout(self.verticalLayout_22)
        spacerItem24 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem24)
        self.horizontalLayout_15.addWidget(self.ind_lvl_ph_mas)
        self.ind_lvl_ph_menos = QtWidgets.QFrame(self.frame_3)
        self.ind_lvl_ph_menos.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_lvl_ph_menos.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_lvl_ph_menos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(190, 0, 170, 255), stop:1 rgba(190, 0, 170, 255));\n"
"")
        self.ind_lvl_ph_menos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_lvl_ph_menos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_lvl_ph_menos.setObjectName("ind_lvl_ph_menos")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.ind_lvl_ph_menos)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        spacerItem25 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem25)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_28 = QtWidgets.QLabel(self.ind_lvl_ph_menos)
        self.label_28.setStyleSheet("background-color: transparent;")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_24.addWidget(self.label_28)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.val_lvl_ph_menos = QtWidgets.QLabel(self.ind_lvl_ph_menos)
        self.val_lvl_ph_menos.setStyleSheet("background-color: transparent;")
        self.val_lvl_ph_menos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_lvl_ph_menos.setObjectName("val_lvl_ph_menos")
        self.horizontalLayout_19.addWidget(self.val_lvl_ph_menos)
        self.label_30 = QtWidgets.QLabel(self.ind_lvl_ph_menos)
        self.label_30.setStyleSheet("background-color: transparent;")
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_19.addWidget(self.label_30)
        self.verticalLayout_24.addLayout(self.horizontalLayout_19)
        self.verticalLayout_23.addLayout(self.verticalLayout_24)
        spacerItem26 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem26)
        self.horizontalLayout_15.addWidget(self.ind_lvl_ph_menos)
        self.ind_lvl_nut = QtWidgets.QFrame(self.frame_3)
        self.ind_lvl_nut.setMinimumSize(QtCore.QSize(100, 120))
        self.ind_lvl_nut.setMaximumSize(QtCore.QSize(100, 120))
        self.ind_lvl_nut.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(17, 17, 17, 255), stop:{stop1} rgba(17, 17, 17, 255), stop:{stop2} rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));\n"
"")
        self.ind_lvl_nut.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ind_lvl_nut.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ind_lvl_nut.setObjectName("ind_lvl_nut")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.ind_lvl_nut)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem27 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem27)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_31 = QtWidgets.QLabel(self.ind_lvl_nut)
        self.label_31.setStyleSheet("background-color: transparent;")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_26.addWidget(self.label_31)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.val_lvl_nut = QtWidgets.QLabel(self.ind_lvl_nut)
        self.val_lvl_nut.setStyleSheet("background-color: transparent;")
        self.val_lvl_nut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.val_lvl_nut.setObjectName("val_lvl_nut")
        self.horizontalLayout_20.addWidget(self.val_lvl_nut)
        self.label_33 = QtWidgets.QLabel(self.ind_lvl_nut)
        self.label_33.setStyleSheet("background-color: transparent;")
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_20.addWidget(self.label_33)
        self.verticalLayout_26.addLayout(self.horizontalLayout_20)
        self.verticalLayout_25.addLayout(self.verticalLayout_26)
        spacerItem28 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem28)
        self.horizontalLayout_15.addWidget(self.ind_lvl_nut)
        self.verticalLayout_29.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QRadioButton{\n"
"color:rgb(218, 0, 55);\n"
"font:87 12pt \"Arial\";\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:30px;\n"
"height: 30px;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"background-color:#00ff00;\n"
"border:5px solid #111111;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: #da0037;\n"
"border: 5px solid #111111;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_21.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setSpacing(20)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.act_leds = QtWidgets.QRadioButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.act_leds.setFont(font)
        self.act_leds.setStyleSheet("QRadioButton{\n"
"color:rgb(255, 255, 255);\n"
"font:87 12pt \"Arial\";\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:30px;\n"
"height: 30px;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"background-color:#00ff00;\n"
"border:5px solid #111111;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: #da0037;\n"
"border: 5px solid #111111;\n"
"}")
        self.act_leds.setCheckable(False)
        self.act_leds.setObjectName("act_leds")
        self.verticalLayout_27.addWidget(self.act_leds)
        self.act_ph_pump_mas = QtWidgets.QRadioButton(self.frame_4)
        self.act_ph_pump_mas.setStyleSheet("QRadioButton{\n"
"color:rgb(255, 255, 255);\n"
"font:87 12pt \"Arial\";\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:30px;\n"
"height: 30px;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"background-color:#00ff00;\n"
"border:5px solid #111111;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: #da0037;\n"
"border: 5px solid #111111;\n"
"}")
        self.act_ph_pump_mas.setCheckable(False)
        self.act_ph_pump_mas.setObjectName("act_ph_pump_mas")
        self.verticalLayout_27.addWidget(self.act_ph_pump_mas)
        self.act_ph_pump_menos = QtWidgets.QRadioButton(self.frame_4)
        self.act_ph_pump_menos.setStyleSheet("QRadioButton{\n"
"color:rgb(255, 255, 255);\n"
"font:87 12pt \"Arial\";\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:30px;\n"
"height: 30px;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"background-color:#00ff00;\n"
"border:5px solid #111111;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: #da0037;\n"
"border: 5px solid #111111;\n"
"}")
        self.act_ph_pump_menos.setCheckable(False)
        self.act_ph_pump_menos.setObjectName("act_ph_pump_menos")
        self.verticalLayout_27.addWidget(self.act_ph_pump_menos)
        self.act_nut_pump = QtWidgets.QRadioButton(self.frame_4)
        self.act_nut_pump.setStyleSheet("QRadioButton{\n"
"color:rgb(255, 255, 255);\n"
"font:87 12pt \"Arial\";\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:30px;\n"
"height: 30px;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"background-color:#00ff00;\n"
"border:5px solid #111111;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: #da0037;\n"
"border: 5px solid #111111;\n"
"}")
        self.act_nut_pump.setCheckable(False)
        self.act_nut_pump.setObjectName("act_nut_pump")
        self.verticalLayout_27.addWidget(self.act_nut_pump)
        self.horizontalLayout_21.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(20)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.act_heater = QtWidgets.QRadioButton(self.frame_4)
        self.act_heater.setStyleSheet("QRadioButton{\n"
"color:rgb(255, 255, 255);\n"
"font:87 12pt \"Arial\";\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:30px;\n"
"height: 30px;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"background-color:#00ff00;\n"
"border:5px solid #111111;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: #da0037;\n"
"border: 5px solid #111111;\n"
"}")
        self.act_heater.setCheckable(False)
        self.act_heater.setObjectName("act_heater")
        self.verticalLayout_28.addWidget(self.act_heater)
        self.act_water_pump = QtWidgets.QRadioButton(self.frame_4)
        self.act_water_pump.setStyleSheet("QRadioButton{\n"
"color:rgb(255, 255, 255);\n"
"font:87 12pt \"Arial\";\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:30px;\n"
"height: 30px;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"background-color:#00ff00;\n"
"border:5px solid #111111;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: #da0037;\n"
"border: 5px solid #111111;\n"
"}")
        self.act_water_pump.setCheckable(False)
        self.act_water_pump.setObjectName("act_water_pump")
        self.verticalLayout_28.addWidget(self.act_water_pump)
        self.act_mix_pump = QtWidgets.QRadioButton(self.frame_4)
        self.act_mix_pump.setStyleSheet("QRadioButton{\n"
"color:rgb(255, 255, 255);\n"
"font:87 12pt \"Arial\";\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:30px;\n"
"height: 30px;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"background-color:#00ff00;\n"
"border:5px solid #111111;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: #da0037;\n"
"border: 5px solid #111111;\n"
"}")
        self.act_mix_pump.setCheckable(False)
        self.act_mix_pump.setObjectName("act_mix_pump")
        self.verticalLayout_28.addWidget(self.act_mix_pump)
        self.act_main_pump = QtWidgets.QRadioButton(self.frame_4)
        self.act_main_pump.setStyleSheet("QRadioButton{\n"
"color:rgb(255, 255, 255);\n"
"font:87 12pt \"Arial\";\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:30px;\n"
"height: 30px;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked{\n"
"background-color:#00ff00;\n"
"border:5px solid #111111;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: #da0037;\n"
"border: 5px solid #111111;\n"
"}")
        self.act_main_pump.setCheckable(False)
        self.act_main_pump.setObjectName("act_main_pump")
        self.verticalLayout_28.addWidget(self.act_main_pump)
        self.horizontalLayout_21.addLayout(self.verticalLayout_28)
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.horizontalLayout_6.setStretch(0, 5)
        self.horizontalLayout_6.setStretch(1, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.graph_main = QtWidgets.QHBoxLayout()
        self.graph_main.setObjectName("graph_main")
        self.horizontalLayout_23.addLayout(self.graph_main)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.verticalLayout_6.setStretch(0, 4)
        self.verticalLayout_6.setStretch(1, 6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_deteccion)
        self.page_base_datos = QtWidgets.QWidget()
        self.page_base_datos.setObjectName("page_base_datos")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.page_base_datos)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.tableWidget = QtWidgets.QTableWidget(self.page_base_datos)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"background-color:rgb(17,17,17);\n"
"color:rgb(0,0,0);\n"
"gridline-color:rgb(130,187,62);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:rgb(130,187,62);\n"
"border: 1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border: 1px solid rgb(130,187,62);\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(17)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        self.verticalLayout_30.addWidget(self.tableWidget)
        self.stackedWidget.addWidget(self.page_base_datos)
        self.page_ajustes = QtWidgets.QWidget()
        self.page_ajustes.setObjectName("page_ajustes")
        self.stackedWidget.addWidget(self.page_ajustes)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_paginas)
        self.verticalLayout.addWidget(self.frame_contenido)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Laboratorio de Innnovación Intel"))
        self.label_3.setText(_translate("MainWindow", "Jardín Vertical"))
        self.btn_inicio.setText(_translate("MainWindow", " Inicio"))
        self.btn_basedatos.setText(_translate("MainWindow", " Base Datos"))
        self.btn_ajustes.setText(_translate("MainWindow", " Ajustes"))
        self.label_4.setText(_translate("MainWindow", "Temperatura"))
        self.val_temp.setText(_translate("MainWindow", "20"))
        self.label_6.setText(_translate("MainWindow", "°C"))
        self.label_7.setText(_translate("MainWindow", "Humedad"))
        self.val_humedad.setText(_translate("MainWindow", "50"))
        self.label_9.setText(_translate("MainWindow", "%"))
        self.label_10.setText(_translate("MainWindow", "Luz"))
        self.val_luz.setText(_translate("MainWindow", "12"))
        self.label_12.setText(_translate("MainWindow", "Lux"))
        self.label_13.setText(_translate("MainWindow", "Ph"))
        self.val_ph.setText(_translate("MainWindow", "7"))
        self.label_15.setText(_translate("MainWindow", "Ph"))
        self.label_16.setText(_translate("MainWindow", "Conductividad"))
        self.val_conductividad.setText(_translate("MainWindow", "50"))
        self.label_18.setText(_translate("MainWindow", "ppm"))
        self.label_19.setText(_translate("MainWindow", "T. Agua"))
        self.val_t_agua.setText(_translate("MainWindow", "20"))
        self.label_21.setText(_translate("MainWindow", "°C"))
        self.label_22.setText(_translate("MainWindow", "Lvl Agua"))
        self.val_lvl_agua.setText(_translate("MainWindow", "50"))
        self.label_24.setText(_translate("MainWindow", "%"))
        self.label_25.setText(_translate("MainWindow", "Lvl Ph+"))
        self.val_lvl_ph_mas.setText(_translate("MainWindow", "8"))
        self.label_27.setText(_translate("MainWindow", "Ph"))
        self.label_28.setText(_translate("MainWindow", "Lvl Ph-"))
        self.val_lvl_ph_menos.setText(_translate("MainWindow", "7"))
        self.label_30.setText(_translate("MainWindow", "Ph"))
        self.label_31.setText(_translate("MainWindow", "Lvl Nut"))
        self.val_lvl_nut.setText(_translate("MainWindow", "50"))
        self.label_33.setText(_translate("MainWindow", "%"))
        self.act_leds.setText(_translate("MainWindow", "LEDS"))
        self.act_ph_pump_mas.setText(_translate("MainWindow", "Ph Pump +"))
        self.act_ph_pump_menos.setText(_translate("MainWindow", "Ph Pump -"))
        self.act_nut_pump.setText(_translate("MainWindow", "Nutrient Pump"))
        self.act_heater.setText(_translate("MainWindow", "Heater"))
        self.act_water_pump.setText(_translate("MainWindow", "Water Pump"))
        self.act_mix_pump.setText(_translate("MainWindow", "Mix Pump"))
        self.act_main_pump.setText(_translate("MainWindow", "Main Pump"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Temperatura"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Humedad"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Luz"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ph"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Conductividad"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "N. Ph+"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "N. Ph"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "N. Ph-"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Lvl. Nut"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Main Pump"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Leds"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Ph+ Pump"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Ph- Pump"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Nut Pump"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Mix Pump"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
